apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: code-judge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: code-judge-sandbox
  name: pod-manager
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "configmaps"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-pod-manager-binding
  namespace: code-judge-sandbox
subjects:
- kind: ServiceAccount
  name: api-service-account
  namespace: code-judge
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
